const productos = [
    {
        Id: 1,
        Stock: 5,
        Nombre: "ShermanS",
        Img: "../ruedas/VeteranShermanS/VeteranShermanS.png",
        Precio: "3000",
        Puntuación: 99.33,
        Fabricante: "Veteran",
        Velocidad_tope: "80 km/h",
        Autonomía_real: "99 km - 141 km",
        Potencia_del_motor: "3000 W",
        Peso: "44.00 kg",
        Tiempo_de_carga_de_fábrica: "6.3h (usando un cargador de 5A)",
        Suspensión: "Personalizada",
        Batería: "3200 Wh (21700)",
        Equipo_de_sonido: "No",
        Pantalla: "LED",
        Diámetro: 20,
        Ancho_del_neumático: 3,
        Tamaño: "(Alto) 592mm x (Ancho) 195mm x (Largo) 500mm",
    },
    {
        Id: 2,
        Stock: 2,
        Nombre: "Patton",
        Precio: "3500",
        Img: "../ruedas/VeteranPatton/VeteranPatton.png",
        Puntuación: 90.45,
        Fabricante: "Veteran",
        Velocidad_tope: "70 km/h",
        Autonomía_real: "75 km - 108 km",
        Potencia_del_motor: "3000 W",
        Peso: "39.00 kg",
        Tiempo_de_carga_de_fábrica: "3.5h (usando un cargador de 5A)",
        Suspensión: "Personalizada",
        Batería: "2220 Wh (21700)",
        Equipo_de_sonido: "No",
        Pantalla: "LED",
        Diámetro: 18,
        Ancho_del_neumático: 3,
        Tamaño: "(Alto) 670mm x (Ancho) 203mm x (Largo) 530mm",
    },
    {
        Id: 3,
        Stock: 6,
        Nombre: "Sherman Max",
        Precio: "3200",
        Img: "../ruedas/VeteranShermanMax/VeteranShermanMax.png",
        Puntuación: 87.06,
        Fabricante: "Veteran",
        Velocidad_tope: "78 km/h",
        Autonomía_real: "120 km - 1718 km",
        Potencia_del_motor: "2800 W",
        Peso: "40.00 kg",
        Tiempo_de_carga_de_fábrica: "7.1h (usando un cargador de 5A)",
        Suspensión: "no",
        Batería: "3600 Wh (8p x 3500 mAh, 21700)",
        Equipo_de_sonido: "No",
        Pantalla: "LED",
        Diámetro: 20,
        Ancho_del_neumático: 3,
        Tamaño: "(Alto) 605mm x (Ancho) 195mm x (Largo) 500mm",
    },
    {
        Id: 4,
        Stock: 2,
        Nombre: "Abrams",
        Precio: "2500",
        Img: "../ruedas/VeteranAbrams/VeteranAbrams.png",
        Puntuación: 88.09,
        Fabricante: "Veteran",
        Velocidad_tope: "80 km/h",
        Autonomía_real: "83 km - 119 km",
        Potencia_del_motor: "3500 W",
        Peso: "44.00 kg",
        Tiempo_de_carga_de_fábrica: "3h (usando un cargador de 9A)",
        Suspensión: "no",
        Batería: "2700 Wh (21700)",
        Equipo_de_sonido: "No",
        Pantalla: "LED",
        Diámetro: 22,
        Ancho_del_neumático: 2.75,
        Tamaño: "(Alto) 660mm x (Ancho) 215mm x (Largo) 620mm",
    },
    {
        Id: 5,
        Stock: 8,
        Nombre: "V13",
        Precio: "3800",
        Img: "../ruedas/ImotionV13/ImotionV13.png",
        Puntuación: 100.45,
        Fabricante: "Inmotion",
        Velocidad_tope: "90 km/h",
        Autonomía_real: "81 km - 116 km",
        Potencia_del_motor: "4500 W",
        Peso: "53.00 kg",
        Tiempo_de_carga_de_fábrica: "4.8h (usando un cargador de 5A)",
        Suspensión: "si",
        Batería: "3024 Wh",
        Equipo_de_sonido: "No",
        Pantalla: "lcd",
        Diámetro: 22,
        Ancho_del_neumático: 3,
        Tamaño: "(Alto) 731mm x (Ancho) 579mm x (Largo) 274mm",
    },
    {
        Id: 6,
        Stock: 4,
        Nombre: "V12 Speed",
        Precio: "2500",
        Img: "../ruedas/InmotionV12/InmotionV12.png",
        Puntuación: 90.95,
        Fabricante: "Inmotion",
        Velocidad_tope: "70 km/h",
        Autonomía_real: "75 km - 107 km",
        Potencia_del_motor: "2500 W",
        Peso: "29.00 kg",
        Tiempo_de_carga_de_fábrica: "7.5h (usando un cargador de 2.3A)",
        Suspensión: "no",
        Batería: "1750 Wh (4p, 21700)",
        Equipo_de_sonido: "4.0 ch",
        Pantalla: "lcd",
        Diámetro: 16,
        Ancho_del_neumático: 3,
        Tamaño: "(Alto) 607mm x (Ancho) 191mm x (Largo) 498mm",
    },
    {
        Id: 7,
        Stock: 7,
        Nombre: "V11",
        Precio: "2000",
        Img: "../ruedas/InmotionV11/InmotionV11.png",
        Puntuación: 85.29,
        Fabricante: "Inmotion",
        Velocidad_tope: "55 km/h",
        Autonomía_real: "66 km - 94 km",
        Potencia_del_motor: "2200 W",
        Peso: "27.00 kg",
        Tiempo_de_carga_de_fábrica: "7.1h (usando un cargador de 2.5A)",
        Suspensión: "Personalizada",
        Batería: "1500 Wh (4p x 5000 mAh, 21700)",
        Equipo_de_sonido: "no",
        Pantalla: "no",
        Diámetro: 18,
        Ancho_del_neumático: 3,
        Tamaño: "(Alto) 676mm x (Ancho) 200mm x (Largo) 500mm",
    },
    {
        Id: 8,
        Stock: 3,
        Nombre: "S22 Pro",
        Precio: "3100",
        Img: "../ruedas/KingSongS22Pro/KingSongS22Pro.png",
        Puntuación: 100.93,
        Fabricante: "Kingsong",
        Velocidad_tope: "70 km/h",
        Autonomía_real: "83 km - 118 km",
        Potencia_del_motor: "4000 W",
        Peso: "35.00 kg",
        Tiempo_de_carga_de_fábrica: "2.9h (usando un cargador de 6A)",
        Suspensión: "Estándar",
        Batería: "2200 Wh (4p, 21700)",
        Equipo_de_sonido: "no",
        Pantalla: "no",
        Diámetro: 20,
        Ancho_del_neumático: 2.75,
        Tamaño: "(Alto) 686mm x (Ancho) 330mm x (Largo) 584mm",
    },
    {
        Id: 9,
        Stock: 9,
        Nombre: "S18",
        Precio: "1800",
        Img: "../ruedas/KingsongS18/KingsongS18.png",
        Puntuación: 74.46,
        Fabricante: "Kingsong",
        Velocidad_tope: "50 km/h",
        Autonomía_real: "49 km - 70km",
        Potencia_del_motor: "2200 W",
        Peso: "25.00 kg",
        Tiempo_de_carga_de_fábrica: "7.6h (usando un cargador de 1.75A))",
        Suspensión: "Estándar",
        Batería: "1110 Wh (3p x 3500 mAh, 18650)",
        Equipo_de_sonido: "no",
        Pantalla: "on",
        Diámetro: 18,
        Ancho_del_neumático: 3,
        Tamaño: "(Alto) 557mm x (Ancho) 200mm x (Largo) 530mm",
    },
    {
        Id: 10,
        Stock: 7,
        Nombre: "18XL",
        Precio: "1500",
        Img: "../ruedas/Kingsong18XL/Kingsong18XL.png",
        Puntuación: 79.95,
        Fabricante: "Kingsong",
        Velocidad_tope: "50 km/h",
        Autonomía_real: "68 km - 97 km",
        Potencia_del_motor: "2000 W",
        Peso: "25.40 kg",
        Tiempo_de_carga_de_fábrica: "12.3h (usando un cargador de 1.5A)",
        Suspensión: "no",
        Batería: "1554 Wh (6p, 18650)",
        Equipo_de_sonido: "4.0 ch",
        Pantalla: "no",
        Diámetro: 18,
        Ancho_del_neumático: 2.5,
        Tamaño: "(Alto) 590mm x (Ancho) 180mm x (Largo) 495mm",
    },
    {
        Id: 11,
        Stock: 10,
        Nombre: "16S",
        Precio: "1500",
        Img: "../ruedas/KingSongKS16S/KingSongKS16S.png",
        Puntuación: 65.71,
        Fabricante: "Kingsong",
        Velocidad_tope: "35 km/h",
        Autonomía_real: "45km - 60km",
        Potencia_del_motor: "1200 W",
        Peso: "17.40kg",
        Tiempo_de_carga_de_fábrica: "6.3h (usando un cargador de 2A)",
        Suspensión: "no",
        Batería: "840 Wh (4p, 18650)",
        Equipo_de_sonido: "2.0 ch",
        Pantalla: "no",
        Diámetro: 16,
        Ancho_del_neumático: 2.13,
        Tamaño: "(Alto) 406mm x (Ancho) 196mm x (Largo) 463mm",
    },
    {
        Id: 12,
        Stock: 11,
        Nombre: "Master Pro",
        Precio: "2500",
        Img: "../ruedas/BegodeMasterPro/BegodeMasterPro.png",
        Puntuación: 102.48,
        Fabricante: "Begode",
        Velocidad_tope: "80 km/h",
        Autonomía_real: "105 km - 150 km",
        Potencia_del_motor: "4500 W",
        Peso: "50kg",
        Tiempo_de_carga_de_fábrica: "11.9h (usando un cargador de 3A)",
        Suspensión: "Estándar",
        Batería: "4800 Wh (4p, 7h (usando un cargador de 5.1A)",
        Equipo_de_sonido: "no",
        Pantalla: "LED",
        Diámetro: 22,
        Ancho_del_neumático: 2.75,
        Tamaño: "(Alto) 780mm x (Ancho) 300mm x (Largo) 560mm",
    },

    {
        Id: 13,
        Stock: 6,
        Nombre: "EX30",
        Precio: "2700",
        Img: "../ruedas/BegodeEX30/BegodeEX30.png",
        Puntuación: 102.27,
        Fabricante: "Begode",
        Velocidad_tope: "80 km/h",
        Autonomía_real: "100 km - 143 km",
        Potencia_del_motor: "4000 W",
        Peso: "46.00 kg",
        Tiempo_de_carga_de_fábrica: "8.9h (usando un cargador de 3A)",
        Suspensión: "Estándar",
        Batería: "3600 Wh (4p, 21700)",
        Equipo_de_sonido: "no",
        Pantalla: "LED",
        Diámetro: 20,
        Ancho_del_neumático: 2.75,
        Tamaño: "(Alto) 550mm x (Ancho) 280mm x (Largo) 770mm",
    },

    {
        Id: 14,
        Stock: 9,
        Nombre: "Mten 4",
        Precio: "1900",
        Img: "../ruedas/BegodeMten4/BegodeMten4.png",
        Puntuación: 66.34,
        Fabricante: "Begode",
        Velocidad_tope: "45 km/h",
        Autonomía_real: "35 km - 50 km",
        Potencia_del_motor: "800 W",
        Peso: "13.00 kg",
        Tiempo_de_carga_de_fábrica: "6h (usando un cargador de 1.5A))",
        Suspensión: "no",
        Batería: "750 Wh (4p, 21700)",
        Equipo_de_sonido: "no",
        Pantalla: "LED",
        Diámetro: 11,
        Ancho_del_neumático: 3,
        Tamaño: "(Alto) 440mm x (Ancho) 200mm x (Largo) 350mm",
    },
];
const getProductos = () => {
    /*     const respuestaRandom = Math.random() > 0.5;     */
    return new Promise((resolve, rejet) => {
        setTimeout(() => {
            resolve(productos);
            /*if (respuestaRandom) {
                
            }   else {
                rejet("error de enla base de datos vuelva a cargar");
            } */
        }, 1000);
    });
};
export { getProductos };

const getProductosFiltrados = (filtro) => {
    return new Promise((resolve, rejet) => {
        setTimeout(() => {
            resolve(
                productos.filter((el) => {
                    return el.Fabricante === filtro;
                })
            );
        }, 1000);
    });
};
export { getProductosFiltrados };

const getProductosById = (idProducto) => {
    return new Promise((resolve, rejet) => {
        setTimeout(() => {
            resolve(
                productos.find((el) => {
                    return el.Id === idProducto;
                })
            );
        }, 1000);
    });
};
export { getProductosById };
